---
# 1. Update API Server 
# -----------------------------------------------------------------------------

# https://github.ibm.com/wiotp/tracker/issues/11556

- name: "Backwards compatability for 'quickburn' cluster type"
  when: cluster_type == "quickburn"
  set_fact:
    cluster_type: "fyre"

# 2. Debug Info
# -----------------------------------------------------------------------------
- name: "fyre : Debug information"
  debug:
    msg:
      - "Cluster type ................. {{ cluster_type }}"
      - "ocp_fips     ................. {{ ocp_fips }}"
# Update API Server to Intermediate to include semeru compatible ciphers
- include_tasks: tasks/update-apiserver.yml
  when:
      - (cluster_type == 'fyre') or (cluster_type == 'aws')
      - ocp_fips
